### ISSUE TITLE
Where are files? Dead links

### ISSUE THREAD

**Issue by Neustradamus** [jmclaren7/simpleuvnc#1]
Where we can download files?
- http://teammc.cc/uvnc/ dead
- https://johnscs.com/uvnc-helper/ dead links on it
- https://github.com/jmclaren7/simpleuvnc dead links on it

**Comment by jmclaren7** [comment]
You'll need to build it yourself, this is an old project that is no longer supported or recommended for use. Everything except binary file should be in this repository. However i doubt it will work with recent versions of UVNC and the versions it was build around will have security and compatibility issues.

**Comment by Neustradamus** [comment]
Can you add existing missing builds?

**Comment by jmclaren7** [comment]
They don't exist, sorry.
